export const database = [
  {
    video_url: 'https://www.youtube.com/watch?v=JyV7mUFSpXs',
    video_type: 'beginner',
    body_part: 'bicep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=20ibpB635Rw',
    video_type: 'beginner',
    body_part: 'bicep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=KzZILhT_YvY&t=11s',
    video_type: 'beginner',
    body_part: 'bicep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=u7MVeTlDX9A',
    video_type: 'beginner',
    body_part: 'bicep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'rest',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=32Sh5yvm4pg',
    video_type: 'beginner',
    body_part: 'bicep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=CKq64fFPqTY',
    video_type: 'beginner',
    body_part: 'bicep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=uBkjIH-9MMI',
    video_type: 'beginner',
    body_part: 'bicep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'rest',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=9gwOrroXyJM',
    video_type: 'intermediate',
    body_part: 'bicep',
    program_title: 'Getting started for bigger arms',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=ymCcs3lhiLs',
    video_type: 'intermediate',
    body_part: 'bicep',
    program_title: 'Getting started for bigger arms',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=51zzhEn8DxM',
    video_type: 'intermediate',
    body_part: 'bicep',
    program_title: 'Getting started for bigger arms',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=vr0mNQR-KZw',
    video_type: 'intermediate',
    body_part: 'bicep',
    program_title: 'Getting started for bigger arms',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=Tw0p3t5kOx0',
    video_type: 'intermediate',
    body_part: 'bicep',
    program_title: 'Getting started for bigger arms',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=MfIH1Gd2b64',
    video_type: 'advanced',
    body_part: 'bicep',
    program_title: 'Big arms challenge',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=WL8z8vK03Po',
    video_type: 'advanced',
    body_part: 'bicep',
    program_title: 'Big arms challenge',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=iGYeHsgb4CY',
    video_type: 'advanced',
    body_part: 'bicep',
    program_title: 'Big arms challenge',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=hiNVt8Q8BuI',
    video_type: 'advanced',
    body_part: 'bicep',
    program_title: 'Big arms challenge',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=B-lZ7jiwiZ0',
    video_type: 'advanced',
    body_part: 'bicep',
    program_title: 'Big arms challenge',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=KzBZ02EAJvE',
    video_type: 'beginner',
    body_part: 'tricep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=RTF4ADblouI',
    video_type: 'beginner',
    body_part: 'tricep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=x-xEKVjJEmc',
    video_type: 'beginner',
    body_part: 'tricep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=u-mMw9T4Ywg',
    video_type: 'beginner',
    body_part: 'tricep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=RI9YPR1RwX0',
    video_type: 'beginner',
    body_part: 'tricep',
    program_title: 'Arms workout for beginner',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=mQjhgi7VI9M',
    video_type: 'intermediate',
    body_part: 'tricep',
    program_title: 'Getting started for bigger arms',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=ZxLoG88KYK4',
    video_type: 'intermediate',
    body_part: 'tricep',
    program_title: 'Getting started for bigger arms',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=SuajkDYlIRw',
    video_type: 'intermediate',
    body_part: 'tricep',
    program_title: 'Getting started for bigger arms',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=30owVlZZEf8',
    video_type: 'intermediate',
    body_part: 'tricep',
    program_title: 'Getting started for bigger arms',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=mapd6vDNJqk',
    video_type: 'intermediate',
    body_part: 'tricep',
    program_title: 'Getting started for bigger arms',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=oQYgTPMxe-Q',
    video_type: 'advanced',
    body_part: 'tricep',
    program_title: 'Big arms challenge',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=GXz-hGbyYpE',
    video_type: 'advanced',
    body_part: 'tricep',
    program_title: 'Big arms challenge',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=woYLmQHyd6o',
    video_type: 'advanced',
    body_part: 'tricep',
    program_title: 'Big arms challenge',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=_-DDjCoMRSI',
    video_type: 'advanced',
    body_part: 'tricep',
    program_title: 'Big arms challenge',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=d24nAtn8w4E',
    video_type: 'advanced',
    body_part: 'tricep',
    program_title: 'Big arms challenge',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=BkS1-El_WlE',
    video_type: 'beginner',
    body_part: 'chest',
    program_title: 'Chest workout for beginner',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=MWR5yscXzsM',
    video_type: 'beginner',
    body_part: 'chest',
    program_title: 'Chest workout for beginner',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=O9K0k7fzrqU',
    video_type: 'beginner',
    body_part: 'chest',
    program_title: 'Chest workout for beginner',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=fZ2cz8xBM1E',
    video_type: 'beginner',
    body_part: 'chest',
    program_title: 'Chest workout for beginner',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=zoKu5Bw9rLU',
    video_type: 'beginner',
    body_part: 'chest',
    program_title: 'Chest workout for beginner',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=Wmj2_8rJlP8',
    video_type: 'intermediate',
    body_part: 'chest',
    program_title: 'Intermediate Chest Builder',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=vO4VfcaosEk',
    video_type: 'intermediate',
    body_part: 'chest',
    program_title: 'Intermediate Chest Builder',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=4o1YzksPuqg',
    video_type: 'intermediate',
    body_part: 'chest',
    program_title: 'Intermediate Chest Builder',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=HU4x9I2L1dk',
    video_type: 'intermediate',
    body_part: 'chest',
    program_title: 'Intermediate Chest Builder',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=EdRkmsnsi58',
    video_type: 'intermediate',
    body_part: 'chest',
    program_title: 'Intermediate Chest Builder',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=J5yQl3r-X_U',
    video_type: 'advanced',
    body_part: 'chest',
    program_title: 'Pro Chest Challenge',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=BB1DbULobdY',
    video_type: 'advanced',
    body_part: 'chest',
    program_title: 'Pro Chest Challenge',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=3QQ6bA8udbU',
    video_type: 'advanced',
    body_part: 'chest',
    program_title: 'Pro Chest Challenge',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=XwSJy-S6oXI',
    video_type: 'advanced',
    body_part: 'chest',
    program_title: 'Pro Chest Challenge',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=iRHLwLm1CX8',
    video_type: 'advanced',
    body_part: 'chest',
    program_title: 'Pro Chest Challenge',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=h1WkC8YT48A',
    video_type: 'beginner',
    body_part: 'shoulder',
    program_title: 'Shoulders workout for beginner',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=oxvYy6DQ-Hk',
    video_type: 'beginner',
    body_part: 'shoulder',
    program_title: 'Shoulders workout for beginner',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=OA2sx4IudYs',
    video_type: 'beginner',
    body_part: 'shoulder',
    program_title: 'Shoulders workout for beginner',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=ccLoSTz0a_I',
    video_type: 'beginner',
    body_part: 'shoulder',
    program_title: 'Shoulders workout for beginner',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=D5aUaAOR4yk',
    video_type: 'beginner',
    body_part: 'shoulder',
    program_title: 'Shoulders workout for beginner',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=QVaijMZ2mp8&t=32s',
    video_type: 'intermediate',
    body_part: 'shoulder',
    program_title: 'Intermediate Shoulder Boost',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=V0dYd1jyLpE',
    video_type: 'intermediate',
    body_part: 'shoulder',
    program_title: 'Intermediate Shoulder Boost',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=LQCXxaHEpRs',
    video_type: 'intermediate',
    body_part: 'shoulder',
    program_title: 'Intermediate Shoulder Boost',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=3QF55ZeDXwg',
    video_type: 'intermediate',
    body_part: 'shoulder',
    program_title: 'Intermediate Shoulder Boost',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=lCuW7GHgMlc',
    video_type: 'intermediate',
    body_part: 'shoulder',
    program_title: 'Intermediate Shoulder Boost',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=zcpYZkBXOxc',
    video_type: 'advanced',
    body_part: 'shoulder',
    program_title: 'Athletes chest workout',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=tkBtxfBY4P8',
    video_type: 'advanced',
    body_part: 'shoulder',
    program_title: 'Athletes chest workout',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=rRd-lDTANO4',
    video_type: 'advanced',
    body_part: 'shoulder',
    program_title: 'Athletes chest workout',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=ZFWSc8D1FWs',
    video_type: 'advanced',
    body_part: 'shoulder',
    program_title: 'Athletes chest workout',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=KFx361_92EU',
    video_type: 'advanced',
    body_part: 'shoulder',
    program_title: 'Athletes chest workout',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=qqEw8XH-feI',
    video_type: 'beginner',
    body_part: 'back',
    program_title: 'Back workout for beginner',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=ClzTDsQDC0E',
    video_type: 'beginner',
    body_part: 'back',
    program_title: 'Back workout for beginner',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=nzEMYwCluZQ',
    video_type: 'beginner',
    body_part: 'back',
    program_title: 'Back workout for beginner',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=_qjBvQ9F4kw',
    video_type: 'beginner',
    body_part: 'back',
    program_title: 'Back workout for beginner',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=mjnseqLiVXM',
    video_type: 'beginner',
    body_part: 'back',
    program_title: 'Back workout for beginner',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=bnLoxTvKmc4',
    video_type: 'intermediate',
    body_part: 'back',
    program_title: 'Intermediate back Builder Challenge',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=P9cnQAfhwIM',
    video_type: 'intermediate',
    body_part: 'back',
    program_title: 'Intermediate back Builder Challenge',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=CFfx-pp8728',
    video_type: 'intermediate',
    body_part: 'back',
    program_title: 'Intermediate back Builder Challenge',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=YvKOvyiAdAI',
    video_type: 'intermediate',
    body_part: 'back',
    program_title: 'Intermediate back Builder Challenge',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=g42CMLdOGnc',
    video_type: 'intermediate',
    body_part: 'back',
    program_title: 'Intermediate back Builder Challenge',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=7VVnTaPzzss',
    video_type: 'advanced',
    body_part: 'back',
    program_title: 'Build back like pro athletes',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=vA5uXiGva1Y',
    video_type: 'advanced',
    body_part: 'back',
    program_title: 'Build back like pro athletes',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=QPKs3989YA0',
    video_type: 'advanced',
    body_part: 'back',
    program_title: 'Build back like pro athletes',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=E0JNbBccexE',
    video_type: 'advanced',
    body_part: 'back',
    program_title: 'Build back like pro athletes',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=T60YhWfv9no',
    video_type: 'advanced',
    body_part: 'back',
    program_title: 'Build back like pro athletes',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=q7rCeOa_m58',
    video_type: 'beginner',
    body_part: 'legs',
    program_title: 'Legs workout for beginner',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=wB9ukMeQfjU',
    video_type: 'beginner',
    body_part: 'legs',
    program_title: 'Legs workout for beginner',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=HG7_XInTExo',
    video_type: 'beginner',
    body_part: 'legs',
    program_title: 'Legs workout for beginner',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=SaohpJ1o_Lg',
    video_type: 'beginner',
    body_part: 'legs',
    program_title: 'Legs workout for beginner',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=G5nxGTFBauM',
    video_type: 'beginner',
    body_part: 'legs',
    program_title: 'Legs workout for beginner',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=WA23NHfNq-s',
    video_type: 'intermediate',
    body_part: 'legs',
    program_title: 'Intermediate Leg Dynamo',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=vK_DQYimccw',
    video_type: 'intermediate',
    body_part: 'legs',
    program_title: 'Intermediate Leg Dynamo',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=l5gWYLJKFwQ',
    video_type: 'intermediate',
    body_part: 'legs',
    program_title: 'Intermediate Leg Dynamo',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=uYkpTWfpFHA',
    video_type: 'intermediate',
    body_part: 'legs',
    program_title: 'Intermediate Leg Dynamo',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=hw3NW5YaYDs',
    video_type: 'intermediate',
    body_part: 'legs',
    program_title: 'Intermediate Leg Dynamo',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=H6mRkx1x77k',
    video_type: 'advanced',
    body_part: 'legs',
    program_title: 'Legendary legs workout',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=H3QfYAGnl5E',
    video_type: 'advanced',
    body_part: 'legs',
    program_title: 'Legendary legs workout',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=_HW0jz00Au4',
    video_type: 'advanced',
    body_part: 'legs',
    program_title: 'Legendary legs workout',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=SDAVyMuPah0',
    video_type: 'advanced',
    body_part: 'legs',
    program_title: 'Legendary legs workout',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=1FgC5DP6Rn0',
    video_type: 'advanced',
    body_part: 'legs',
    program_title: 'Legendary legs workout',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=_hIFF8G-BG0',
    video_type: 'beginner',
    body_part: 'glutes',
    program_title: 'Glutes workout for beginner',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=6pKKnVg1hzE',
    video_type: 'beginner',
    body_part: 'glutes',
    program_title: 'Glutes workout for beginner',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=qmO6ulKZScE',
    video_type: 'beginner',
    body_part: 'glutes',
    program_title: 'Glutes workout for beginner',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=GHBVM3P63ds',
    video_type: 'beginner',
    body_part: 'glutes',
    program_title: 'Glutes workout for beginner',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=N9_11gKQGqM',
    video_type: 'beginner',
    body_part: 'glutes',
    program_title: 'Glutes workout for beginner',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=oxdQBVlrEyI',
    video_type: 'intermediate',
    body_part: 'glute',
    program_title: 'Bubble butt program',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=uAkgoRhHdS0',
    video_type: 'intermediate',
    body_part: 'glute',
    program_title: 'Bubble butt program',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=HM4wPB3nU2M',
    video_type: 'intermediate',
    body_part: 'glute',
    program_title: 'Bubble butt program',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=nToYLalDBI0',
    video_type: 'intermediate',
    body_part: 'glute',
    program_title: 'Bubble butt program',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=HzRwKt2NLQ8&t=16s',
    video_type: 'intermediate',
    body_part: 'glute',
    program_title: 'Bubble butt program',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=o0a8Ohx4jbQ',
    video_type: 'advanced',
    body_part: 'glute',
    program_title: 'Killer butt program',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=A-kJok1nhv4',
    video_type: 'advanced',
    body_part: 'glute',
    program_title: 'Killer butt program',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=U-hag4iT7V8',
    video_type: 'advanced',
    body_part: 'glute',
    program_title: 'Killer butt program',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=6vlP9xPJbaQ',
    video_type: 'advanced',
    body_part: 'glute',
    program_title: 'Killer butt program',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=8lj6Al0SaIY',
    video_type: 'advanced',
    body_part: 'glute',
    program_title: 'Killer butt program',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=2pLT-olgUJs',
    video_type: 'beginner',
    body_part: 'abs',
    program_title: 'Abs workout for beginner',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=rptV4dEJUx4',
    video_type: 'beginner',
    body_part: 'abs',
    program_title: 'Abs workout for beginner',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=8PwoytUU06g',
    video_type: 'beginner',
    body_part: 'abs',
    program_title: 'Abs workout for beginner',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=gU-MuOGc9KA',
    video_type: 'beginner',
    body_part: 'abs',
    program_title: 'Abs workout for beginner',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=NdxecB43PgU',
    video_type: 'beginner',
    body_part: 'abs',
    program_title: 'Abs workout for beginner',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=XZYpUkUpYvk',
    video_type: 'intermediate',
    body_part: 'abs',
    program_title: 'Models abs workout',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=QdIutxfm_hU',
    video_type: 'intermediate',
    body_part: 'abs',
    program_title: 'Models abs workout',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=BdhqubW1GJE',
    video_type: 'intermediate',
    body_part: 'abs',
    program_title: 'Models abs workout',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=RKqb61-zTyY',
    video_type: 'intermediate',
    body_part: 'abs',
    program_title: 'Models abs workout',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=gxnYoddQIk0',
    video_type: 'intermediate',
    body_part: 'abs',
    program_title: 'Models abs workout',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=k1cLRd7cahQ',
    video_type: 'advanced',
    body_part: 'abs',
    program_title: 'Greek god abs',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=yDWm37koq3A',
    video_type: 'advanced',
    body_part: 'abs',
    program_title: 'Greek god abs',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=R8oZk2wnpY0',
    video_type: 'advanced',
    body_part: 'abs',
    program_title: 'Greek god abs',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=WoMxD3x4g7U',
    video_type: 'advanced',
    body_part: 'abs',
    program_title: 'Greek god abs',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=IrA9dvgRKR0',
    video_type: 'advanced',
    body_part: 'abs',
    program_title: 'Greek god abs',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=-YJXpabrX4k',
    video_type: 'beginner',
    body_part: 'cardio',
    program_title: 'Low Impact cardio workout',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=50kH47ZztHs',
    video_type: 'beginner',
    body_part: 'cardio',
    program_title: 'Low Impact cardio workout',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=IvmaekQfKiw',
    video_type: 'beginner',
    body_part: 'cardio',
    program_title: 'Low Impact cardio workout',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=zXK6oXwRr1U',
    video_type: 'beginner',
    body_part: 'cardio',
    program_title: 'Low Impact cardio workout',
    schedule_title: 'day4',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=VWj8ZxCxrYk',
    video_type: 'beginner',
    body_part: 'cardio',
    program_title: 'Low Impact cardio workout',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=D2xTsTPkL4M',
    video_type: 'beginner',
    body_part: 'cardio',
    program_title: 'Low Impact cardio workout',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=wLYeRlyyncY',
    video_type: 'intermediate',
    body_part: 'cardio',
    program_title: 'Intermediate Cardio workout',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=fcN37TxBE_s',
    video_type: 'intermediate',
    body_part: 'cardio',
    program_title: 'Intermediate Cardio workout',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=8MImdWV2WfI',
    video_type: 'intermediate',
    body_part: 'cardio',
    program_title: 'Intermediate Cardio workout',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=Ba3qZjzPonI',
    video_type: 'intermediate',
    body_part: 'cardio',
    program_title: 'Intermediate Cardio workout',
    schedule_title: 'day4',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=Gt4OlweHzNk',
    video_type: 'intermediate',
    body_part: 'cardio',
    program_title: 'Intermediate Cardio workout',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=aW5IYarq0fo',
    video_type: 'intermediate',
    body_part: 'cardio',
    program_title: 'Intermediate Cardio workout',
    schedule_title: 'day6',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=79cx5vmf3Qg',
    video_type: 'advanced',
    body_part: 'cardio',
    program_title: 'Intense cardio workout',
    schedule_title: 'day1',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=yplP5cLuyf4',
    video_type: 'advanced',
    body_part: 'cardio',
    program_title: 'Intense cardio workout',
    schedule_title: 'day2',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=gyHUvbVfhdw',
    video_type: 'advanced',
    body_part: 'cardio',
    program_title: 'Intense cardio workout',
    schedule_title: 'day3',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=-hSma-BRzoo',
    video_type: 'advanced',
    body_part: 'cardio',
    program_title: 'Intense cardio workout',
    schedule_title: 'day4',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=bbVJUxQSJME',
    video_type: 'advanced',
    body_part: 'cardio',
    program_title: 'Intense cardio workout',
    schedule_title: 'day5',
  },
  {
    video_url: 'https://www.youtube.com/watch?v=FeR-4_Opt-g',
    video_type: 'advanced',
    body_part: 'cardio',
    program_title: 'Intense cardio workout',
    schedule_title: 'day6',
  },
]
